---
abstract: 'Use Perl::Metrics::Lite in test programs'
author:
  - 'Dann <techmemo@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Perl-Metrics-Lite
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Perl::Metrics::Lite: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
